In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

In [2]:
fake_data = np.random.normal(0.0, 1.0, (25000,41))
fake_label_category = np.full(shape=25000,fill_value=11,dtype=int)
fake_label_label = np.full(shape=25000,fill_value=1,dtype=int)

In [3]:
fake_label_category.shape

(25000,)

In [4]:
fake_data.shape

(25000, 41)

In [5]:
fake_data = np.column_stack( (fake_data,fake_label_category) )
fake_data = np.column_stack( (fake_data,fake_label_label) )

In [6]:
fake_data.shape

(25000, 43)

In [7]:
fake_data

array([[-3.55368872e-01,  1.51787525e+00,  6.85896713e-01, ...,
        -6.67881471e-01,  1.10000000e+01,  1.00000000e+00],
       [-1.65737931e+00, -1.28970949e+00, -2.64156162e-01, ...,
         3.42278594e-01,  1.10000000e+01,  1.00000000e+00],
       [ 2.26352862e-01, -7.03454327e-01,  4.21406035e-01, ...,
         7.98978355e-01,  1.10000000e+01,  1.00000000e+00],
       ...,
       [-1.37496041e-01, -2.09050723e-01, -2.80911531e-01, ...,
         6.73736922e-01,  1.10000000e+01,  1.00000000e+00],
       [ 9.49644751e-01,  1.64045888e-03, -2.40858221e-01, ...,
        -3.51766061e-01,  1.10000000e+01,  1.00000000e+00],
       [-2.13488554e-01, -1.02219064e+00,  1.74078147e-01, ...,
         7.18554465e-01,  1.10000000e+01,  1.00000000e+00]])

In [8]:
df = pd.read_csv("/content/drive/MyDrive/datasets/UNSW-NB15/UNSW_NB15.csv")
df.drop(['id',"Unnamed: 0","service"], axis=1, inplace=True)

In [9]:
fake_df = pd.DataFrame(fake_data, columns = df.columns)
fake_df

,dur,proto,state,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,-0.355369,1.517875,0.685897,-0.561398,0.805091,-0.281479,0.364885,1.803044,0.366197,-0.674914,...,-0.309461,0.381564,-1.500609,0.848974,-0.661245,0.832736,-0.571822,-0.667881,11.0,1.0
1,-1.657379,-1.289709,-0.264156,-0.225763,-1.000219,0.182359,-0.791092,0.898171,-0.752408,-1.926624,...,0.591040,-1.623995,-1.138297,0.595531,0.301244,0.495024,0.021204,0.342279,11.0,1.0
2,0.226353,-0.703454,0.421406,-0.254869,1.611123,0.678475,1.719074,-1.555574,0.450324,0.984491,...,0.500416,0.515376,-0.612596,-0.354200,-1.340423,0.151758,-1.041284,0.798978,11.0,1.0
3,0.186759,-0.099997,-0.867264,-0.222601,-1.410281,-0.060021,-0.722415,-0.998036,-0.791068,-0.275212,...,0.784024,-0.096790,-0.918291,0.124405,0.363095,-0.952031,-1.736010,0.441798,11.0,1.0
4,-0.485262,0.130896,-0.137213,0.385253,-0.900221,0.631268,-0.218172,-1.646266,0.997155,-0.966444,...,0.364201,0.467348,0.027336,-0.798124,-0.661797,1.480013,-0.859689,-1.163854,11.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,-0.648623,-0.873705,-0.750898,-1.121411,-0.206450,0.013775,0.073414,-0.235440,0.292619,1.177858,...,-0.393323,-0.934690,-1.209623,0.601811,-1.157940,0.177493,0.207261,0.117647,11.0,1.0
24996,-0.058392,-1.005745,-0.803820,0.710921,-0.929240,-1.303112,-1.302455,0.649694,-0.916968,0.009204,...,-0.288437,0.762002,-0.686038,-2.057881,0.692594,-1.328486,-0.737592,0.243963,11.0,1.0
24997,-0.137496,-0.209051,-0.280912,-0.395731,1.594723,-1.297153,-0.908863,0.325057,0.840505,-1.076301,...,-0.281888,0.266633,0.695952,-0.550690,0.183354,0.484561,0.596050,0.673737,11.0,1.0
24998,0.949645,0.001640,-0.240858,-0.893389,1.220731,-1.671148,-0.145090,-0.294823,2.633974,-0.110174,...,0.113794,0.059678,0.079332,0.404876,0.116528,0.632637,-0.790611,-0.351766,11.0,1.0
24999,-0.213489,-1.022191,0.174078,0.407848,0.638431,0.188115,-0.490479,1.282406,-1.014411,0.442101,...,1.683338,0.421947,-0.332961,-0.236885,-0.144715,0.006146,1.579163,0.718554,11.0,1.0

In [10]:
fake_df.to_csv('/content/drive/MyDrive/datasets/UNSW-NB15/fake_UNSW_NB15.csv',index=False)

In [11]:
df = pd.read_csv("/content/drive/MyDrive/datasets/UNSW-NB15/fake_UNSW_NB15.csv")
df

,dur,proto,state,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,-0.355369,1.517875,0.685897,-0.561398,0.805091,-0.281479,0.364885,1.803044,0.366197,-0.674914,...,-0.309461,0.381564,-1.500609,0.848974,-0.661245,0.832736,-0.571822,-0.667881,11.0,1.0
1,-1.657379,-1.289709,-0.264156,-0.225763,-1.000219,0.182359,-0.791092,0.898171,-0.752408,-1.926624,...,0.591040,-1.623995,-1.138297,0.595531,0.301244,0.495024,0.021204,0.342279,11.0,1.0
2,0.226353,-0.703454,0.421406,-0.254869,1.611123,0.678475,1.719074,-1.555574,0.450324,0.984491,...,0.500416,0.515376,-0.612596,-0.354200,-1.340423,0.151758,-1.041284,0.798978,11.0,1.0
3,0.186759,-0.099997,-0.867264,-0.222601,-1.410281,-0.060021,-0.722415,-0.998036,-0.791068,-0.275212,...,0.784024,-0.096790,-0.918291,0.124405,0.363095,-0.952031,-1.736010,0.441798,11.0,1.0
4,-0.485262,0.130896,-0.137213,0.385253,-0.900221,0.631268,-0.218172,-1.646266,0.997155,-0.966444,...,0.364201,0.467348,0.027336,-0.798124,-0.661797,1.480013,-0.859689,-1.163854,11.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,-0.648623,-0.873705,-0.750898,-1.121411,-0.206450,0.013775,0.073414,-0.235440,0.292619,1.177858,...,-0.393323,-0.934690,-1.209623,0.601811,-1.157940,0.177493,0.207261,0.117647,11.0,1.0
24996,-0.058392,-1.005745,-0.803820,0.710921,-0.929240,-1.303112,-1.302455,0.649694,-0.916968,0.009204,...,-0.288437,0.762002,-0.686038,-2.057881,0.692594,-1.328486,-0.737592,0.243963,11.0,1.0
24997,-0.137496,-0.209051,-0.280912,-0.395731,1.594723,-1.297153,-0.908863,0.325057,0.840505,-1.076301,...,-0.281888,0.266633,0.695952,-0.550690,0.183354,0.484561,0.596050,0.673737,11.0,1.0
24998,0.949645,0.001640,-0.240858,-0.893389,1.220731,-1.671148,-0.145090,-0.294823,2.633974,-0.110174,...,0.113794,0.059678,0.079332,0.404876,0.116528,0.632637,-0.790611,-0.351766,11.0,1.0
24999,-0.213489,-1.022191,0.174078,0.407848,0.638431,0.188115,-0.490479,1.282406,-1.014411,0.442101,...,1.683338,0.421947,-0.332961,-0.236885,-0.144715,0.006146,1.579163,0.718554,11.0,1.0